# Copy this to credentials.yml and fill with your own data

# https://developers.facebook.com/apps
facebook:
  access_token: abc

# To register your application with Azure DataMarket,
# visit https://datamarket.azure.com/developer/applications/
# This is needed for Bing Translate API
azure:
  client_id: abc
  client_secret: abc