- name: Teekkariravintolat
  address: Otakaari 24, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00, Sat 11:30-15:00
  url:
    fi: http://www.sodexo.fi/dipoli

- name: TUAS-talo
  address: Otaniementie 17, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-16:00, Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/TUAS
    en: http://www.amica.fi/en/TUAS

- name: Alvari
  address: Otakaari 2, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-17:00, Fri 10:30-15:00
  url:
    fi: http://www.amica.fi/alvari
    en: http://www.amica.fi/en/alvari

- name: Elissa
  address: Otakaari 2, Espoo
  campus: Otaniemi
  open: Mon-Thu 08:00-18:00, Fri 08:00-15:00
  url:
    fi: http://www.amica.fi/elissa

- name: Täffä
  address: Otakaari 22, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: https://www.teknologforeningen.fi/index.php?option=com_content&view=article&id=277&Itemid=128&lang=fi
    en: https://www.teknologforeningen.fi/index.php?option=com_content&view=article&id=277&Itemid=128&lang=en

- name: Puu
  address: Tekniikantie 3, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:30-13:30
  url:
    fi: http://www.amica.fi/Puu2

- name: Kvarkki
  address: Otakaari 3, Espoo
  campus: Otaniemi
  open: Mon-Thu 10:30-16:00, Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/kvarkki
    en: http://www.amica.fi/en/kvarkki

- name: Silinteri
  address: Otakaari 1 D, Espoo
  campus: Otaniemi
  open: Mon-Fri 10:45-14:00
  url:
    fi: http://www.amica.fi/silinteri

- name: Cantina
  address: Otakaari 24, Espoo
  campus: Otaniemi
  open: Mon-Thu 11:00-22:30, Fri 11:00-22:30, Sat 11:00-17:00
  url:
    fi: http://www.sodexo.fi/cantina

- name: Laurea Otaniemi
  address: Metsänpojankuja 3, Espoo
  campus: Otaniemi
  open: Mon-Thu 11:00-13:15, Fri 11:00-13:00
  url:
    fi: http://www.amica.fi/laureaotaniemi

# - name: Katri Antell Otaniemi
#   address: Lämpömiehenkuja 2, Espoo
#   campus: Otaniemi
#   open: Mon-Fri 11:00-14:00
#   url:
#     fi: http://www.antell.fi/docs/lunch.php?Antell-ravintola%20Aalto%20yliopisto

- name: Rafla
  address: Runeberginkatu 14, Helsinki
  campus: Töölö
  open: Mon-Fri 10:30-16:15
  url:
    fi: http://www.amica.fi/rafla
    en: http://www.amica.fi/en/rafla

- name: Chydenia
  address: Runeberginkatu 22, Helsinki
  campus: Töölö
  open: Mon-Thu 11:00-14:30, Fri 11:00-14:00
  url:
    fi: http://www.amica.fi/chydenia
    en: http://www.amica.fi/en/chydenia

- name: Hanken
  address: Arkadiankatu 22, Helsinki
  campus: Töölö
  open: Mon-Fri 11:00-15:00
  url:
    fi: http://www.amica.fi/hanken
    en: http://www.amica.fi/en/hanken

- name: Sibelius-Akatemia / R-Talo
  address: Pohjoinen Rautatiekatu 9, Helsinki
  campus: Töölö
  open: Mon-Thu 10:30-15:00, Fri 10:30-14:30
  url:
    fi: http://www.amica.fi/r-talo
    en: http://www.amica.fi/en/r-talo

- name: Cafe da Capo
  address: Töölönkatu 28, Helsinki
  campus: Töölö
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: http://www.amica.fi/cafedacapo
    en: http://www.amica.fi/en/cafedacapo

- name: HYSn Osakuntabaari
  address: Urho Kekkosen katu 4-6 D, Helsinki
  campus: Töölö
  open: Mon-Thu 11:00-15:30, Fri 11:00-15:00
  url:
    fi: http://www.hys.net/opiskelijapalvelut/osakuntabaari/ruokalista

# - name: Musiikkitalon Ravintola
#   address: Mannerheimintie 13, Helsinki
#   campus: Töölö
#   open: Mon-Fri 11:00-15:00
#   url:
#     fi: http://www.tapahtumaravintolat.fi/musiikkitalo/fi_FI/etusivu/

- name: Kipsari
  address: Hämeentie 135 E, Helsinki
  campus: Arabia
  open: Mon-Fri 08:00-19:00
  url:
    fi: https://www.facebook.com/kipsari

- name: Meccala
  address: Hämeentie 135 C, Helsinki
  campus: Arabia
  open: Mon-Thu 10:30-14:15, Fri 10:30-14:00
  url:
    fi: http://www.amica.fi/meccala
    en: http://www.amica.fi/en/meccala

# - name: Ravintola Arabianranta
#   address: Hämeentie 135 A, Helsinki
#   campus: Arabia
#   open: Mon-Fri 10:30-13:30
#   url:
#     fi: http://www.compass-group.fi/ravintolat/Helsinki/ravintola-arabianranta/Lounaslista/

- name: Unicafe Chemicum
  address: A.I. Virtasen aukio 1, Helsinki
  campus: Kumpula
  open: Mon-Thu 10:30-15:30, Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/10/
    en: http://www.hyyravintolat.fi/rss/eng/10/

- name: Unicafe Exactum
  address: Gustaf Hällströmin katu 2 B, Helsinki
  campus: Kumpula
  open: Mon-Fri 11:00-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/11/
    en: http://www.hyyravintolat.fi/rss/eng/11/

- name: Unicafe Metsätalo
  address: Fabianinkatu 39, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/1/
    en: http://www.hyyravintolat.fi/rss/eng/1/

- name: Unicafe Olivia
  address: Siltavuorenpenger 5 A, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:00, Fri 10:30-15:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/2/
    en: http://www.hyyravintolat.fi/rss/eng/2/

- name: Unicafe Porthania
  address: Yliopistonkatu 3, Helsinki
  campus: Keskusta
  open: Mon-Thu 10:30-16:30, Fri 10:30-16:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/3/
    en: http://www.hyyravintolat.fi/rss/eng/3/

- name: Unicafe Päärakennus
  address: Fabianinkatu 33, Helsinki
  campus: Keskusta
  open: Mon-Fri 10:30-16:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/4/
    en: http://www.hyyravintolat.fi/rss/eng/4/

- name: Unicafe Rotunda
  address: Unioninkatu 36, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-13:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/5/
    en: http://www.hyyravintolat.fi/rss/eng/5/

- name: Unicafe Soc&Kom
  address: Yrjö-Koskisen katu 3, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/15/
    en: http://www.hyyravintolat.fi/rss/eng/15/

- name: Unicafe Topelias
  address: Unioninkatu 38, Helsinki
  campus: Keskusta
  open: Mon-Thu 11:00-14:30, Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/6/
    en: http://www.hyyravintolat.fi/rss/eng/6/

- name: Unicafe Valtiotiede
  address: Unioninkatu 37, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/7/
    en: http://www.hyyravintolat.fi/rss/eng/7/

- name: Unicafe Ylioppilasaukio
  address: Mannerheimintie 3 B, Helsinki
  campus: Keskusta
  open: Mon-Fri 11:00-19:00, Sat 11:00-18:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/8/
    en: http://www.hyyravintolat.fi/rss/eng/8/

- name: Kasvisbaari
  address: Kaikukatu 4 B, Helsinki
  campus: Kallio
  open: Mon-Fri 11:00-16:00
  url:
    fi: http://www.kasvisbaari.fi/menu.php

- name: Unicafe Kookos
  address: Haapaniemenkatu 6, Helsinki
  campus: Kallio
  open: Mon-Thu 11:00-17:00, Fri 11:00-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/16/
    en: http://www.hyyravintolat.fi/rss/eng/16/

- name: Unicafe Biokeskus
  address: Viikinkaari 9, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-15:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/18/
    en: http://www.hyyravintolat.fi/rss/eng/18/

- name: Unicafe Korona
  address: Viikinkaari 11, Helsinki
  campus: Viikki
  open: Mon-Fri 11:00-14:00
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/19/
    en: http://www.hyyravintolat.fi/rss/eng/19/

- name: Unicafe Viikuna
  address: Agnes Sjöbergin katu 2, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-14:30
  url:
    fi: http://www.hyyravintolat.fi/rss/fin/21/
    en: http://www.hyyravintolat.fi/rss/eng/21/

- name: Tähkä
  address: Koetilantie 7, Helsinki
  campus: Viikki
  open: Mon-Thu 10:30-13:30, Fri 10:30-13:00
  url:
    fi: http://www.amica.fi/tahka

- name: Ladonlukko
  address: Latokartanonkaari 9 A, Helsinki
  campus: Viikki
  open: Mon-Fri 10:30-14:30
  url:
    fi: http://www.sodexo.fi/ravintolaladonlukko
